server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/foodcourt}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
  flyway:
    enabled: true

clients:
  users:
    base-url: ${USERS_SERVICE_URL:http://localhost:8081/api/v1}

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
  api-docs:
    enabled: false

appDescription: "Microservice for Food Court Restaurant Management"
appVersion: "1.0.0"
